# DO NOT CHANGE THIS
config: "1"
# DO NOT CHANGE THIS

############
## CONFIG ##
############

commands:
  grindstone:
    aliases:
      - grindstone
      - grind
      - gs
  smithing:
    aliases:
      - smith
      - sm
  stonecutter:
    aliases:
      - stonecutter
      - stonecut
      - sc
  enderchest:
    aliases:
      - enderchest
      - echest
      - ec
  workbench:
    aliases:
      - workbench
      - wb
      - work

grindstoneRecipe:
  enabled: true
  recipies:
    - "OAK_LOG:1:OAK_WOOD:4"
    - "OAK_WOOD:1:OAK_LOG:4"

stonecutterRecipe:
  enabled: true
  recipies:
    # log and wood to planks
    ## oak
    - "OAK_LOG:OAK_PLANKS:4"
    - "OAK_WOOD:OAK_PLANKS:4"
    - "STRIPPED_OAK_LOG:OAK_PLANKS:4"
    - "STRIPPED_OAK_WOOD:OAK_PLANKS:4"

    ## spruce
    - "SPRUCE_LOG:SPRUCE_PLANKS:4"
    - "SPRUCE_WOOD:SPRUCE_PLANKS:4"
    - "STRIPPED_SPRUCE_LOG:SPRUCE_PLANKS:4"
    - "STRIPPED_SPRUCE_WOOD:SPRUCE_PLANKS:4"

    ## birch
    - "BIRCH_LOG:BIRCH_PLANKS:4"
    - "BIRCH_WOOD:BIRCH_PLANKS:4"
    - "STRIPPED_BIRCH_LOG:BIRCH_PLANKS:4"
    - "STRIPPED_BIRCH_WOOD:BIRCH_PLANKS:4"

    ## jungle
    - "JUNGLE_LOG:JUNGLE_PLANKS:4"
    - "JUNGLE_WOOD:JUNGLE_PLANKS:4"
    - "STRIPPED_JUNGLE_LOG:JUNGLE_PLANKS:4"
    - "STRIPPED_JUNGLE_WOOD:JUNGLE_PLANKS:4"

    ## acacia
    - "ACACIA_LOG:ACACIA_PLANKS:4"
    - "ACACIA_WOOD:ACACIA_PLANKS:4"
    - "STRIPPED_ACACIA_LOG:ACACIA_PLANKS:4"
    - "STRIPPED_ACACIA_WOOD:ACACIA_PLANKS:4"

    ## dark oak
    - "DARK_OAK_LOG:DARK_OAK_PLANKS:4"
    - "DARK_OAK_WOOD:DARK_OAK_PLANKS:4"
    - "STRIPPED_DARK_OAK_LOG:DARK_OAK_PLANKS:4"
    - "STRIPPED_DARK_OAK_WOOD:DARK_OAK_PLANKS:4"

    ## crimson
    - "CRIMSON_STEM:CRIMSON_PLANKS:4"
    - "CRIMSON_HYPHAE:CRIMSON_PLANKS:4"

    ## warped
    - "WARPED_STEM:WARPED_PLANKS:4"
    - "WARPED_HYPHAE:WARPED_PLANKS:4"

    ## mangrove
    - "MANGROVE_LOG:MANGROVE_PLANKS:4"
    - "MANGROVE_WOOD:MANGROVE_PLANKS:4"
    - "STRIPPED_MANGROVE_LOG:MANGROVE_PLANKS:4"
    - "STRIPPED_MANGROVE_WOOD:MANGROVE_PLANKS:4"

    ## cherry
    - "CHERRY_LOG:CHERRY_PLANKS:4"
    - "CHERRY_WOOD:CHERRY_PLANKS:4"
    - "STRIPPED_CHERRY_LOG:CHERRY_PLANKS:4"
    - "STRIPPED_CHERRY_WOOD:CHERRY_PLANKS:4"

    ## bamboo
    - "BAMBOO_BLOCK:BAMBOO_PLANKS:2"

    # Wood items from planks
    ## oak
    - "OAK_PLANKS:OAK_BUTTON:4"
    - "OAK_PLANKS:OAK_DOOR:1"
    - "OAK_PLANKS:OAK_FENCE:1"
    - "OAK_PLANKS:OAK_FENCE_GATE:1"
    - "OAK_PLANKS:OAK_HANGING_SIGN:1"
    - "OAK_PLANKS:OAK_PRESSURE_PLATE:1"
    - "OAK_PLANKS:OAK_SIGN:1"
    - "OAK_PLANKS:OAK_SLAB:2"
    - "OAK_PLANKS:OAK_STAIRS:1"
    - "OAK_PLANKS:OAK_TRAPDOOR:1"
    - "OAK_PLANKS:OAK_SHELF:1"

    ## spruce
    - "SPRUCE_PLANKS:SPRUCE_BUTTON:4"
    - "SPRUCE_PLANKS:SPRUCE_DOOR:1"
    - "SPRUCE_PLANKS:SPRUCE_FENCE:1"
    - "SPRUCE_PLANKS:SPRUCE_FENCE_GATE:1"
    - "SPRUCE_PLANKS:SPRUCE_HANGING_SIGN:1"
    - "SPRUCE_PLANKS:SPRUCE_PRESSURE_PLATE:1"
    - "SPRUCE_PLANKS:SPRUCE_SIGN:1"
    - "SPRUCE_PLANKS:SPRUCE_SLAB:2"
    - "SPRUCE_PLANKS:SPRUCE_STAIRS:1"
    - "SPRUCE_PLANKS:SPRUCE_TRAPDOOR:1"
    - "SPRUCE_PLANKS:SPRUCE_SHELF:1"

    ## birch
    - "BIRCH_PLANKS:BIRCH_BUTTON:4"
    - "BIRCH_PLANKS:BIRCH_DOOR:1"
    - "BIRCH_PLANKS:BIRCH_FENCE:1"
    - "BIRCH_PLANKS:BIRCH_FENCE_GATE:1"
    - "BIRCH_PLANKS:BIRCH_HANGING_SIGN:1"
    - "BIRCH_PLANKS:BIRCH_PRESSURE_PLATE:1"
    - "BIRCH_PLANKS:BIRCH_SIGN:1"
    - "BIRCH_PLANKS:BIRCH_SLAB:2"
    - "BIRCH_PLANKS:BIRCH_STAIRS:1"
    - "BIRCH_PLANKS:BIRCH_TRAPDOOR:1"
    - "BIRCH_PLANKS:BIRCH_SHELF:1"

    ## jungle
    - "JUNGLE_PLANKS:JUNGLE_BUTTON:4"
    - "JUNGLE_PLANKS:JUNGLE_DOOR:1"
    - "JUNGLE_PLANKS:JUNGLE_FENCE:1"
    - "JUNGLE_PLANKS:JUNGLE_FENCE_GATE:1"
    - "JUNGLE_PLANKS:JUNGLE_HANGING_SIGN:1"
    - "JUNGLE_PLANKS:JUNGLE_PRESSURE_PLATE:1"
    - "JUNGLE_PLANKS:JUNGLE_SIGN:1"
    - "JUNGLE_PLANKS:JUNGLE_SLAB:2"
    - "JUNGLE_PLANKS:JUNGLE_STAIRS:1"
    - "JUNGLE_PLANKS:JUNGLE_TRAPDOOR:1"
    - "JUNGLE_PLANKS:JUNGLE_SHELF:1"

    ## acacia
    - "ACACIA_PLANKS:ACACIA_BUTTON:4"
    - "ACACIA_PLANKS:ACACIA_DOOR:1"
    - "ACACIA_PLANKS:ACACIA_FENCE:1"
    - "ACACIA_PLANKS:ACACIA_FENCE_GATE:1"
    - "ACACIA_PLANKS:ACACIA_HANGING_SIGN:1"
    - "ACACIA_PLANKS:ACACIA_PRESSURE_PLATE:1"
    - "ACACIA_PLANKS:ACACIA_SIGN:1"
    - "ACACIA_PLANKS:ACACIA_SLAB:2"
    - "ACACIA_PLANKS:ACACIA_STAIRS:1"
    - "ACACIA_PLANKS:ACACIA_TRAPDOOR:1"
    - "ACACIA_PLANKS:ACACIA_SHELF:1"

    ## dark oak
    - "DARK_OAK_PLANKS:DARK_OAK_BUTTON:4"
    - "DARK_OAK_PLANKS:DARK_OAK_DOOR:1"
    - "DARK_OAK_PLANKS:DARK_OAK_FENCE:1"
    - "DARK_OAK_PLANKS:DARK_OAK_FENCE_GATE:1"
    - "DARK_OAK_PLANKS:DARK_OAK_HANGING_SIGN:1"
    - "DARK_OAK_PLANKS:DARK_OAK_PRESSURE_PLATE:1"
    - "DARK_OAK_PLANKS:DARK_OAK_SIGN:1"
    - "DARK_OAK_PLANKS:DARK_OAK_SLAB:2"
    - "DARK_OAK_PLANKS:DARK_OAK_STAIRS:1"
    - "DARK_OAK_PLANKS:DARK_OAK_TRAPDOOR:1"
    - "DARK_OAK_PLANKS:DARK_OAK_SHELF:1"

    ## crimson
    - "CRIMSON_PLANKS:CRIMSON_BUTTON:4"
    - "CRIMSON_PLANKS:CRIMSON_DOOR:1"
    - "CRIMSON_PLANKS:CRIMSON_FENCE:1"
    - "CRIMSON_PLANKS:CRIMSON_FENCE_GATE:1"
    - "CRIMSON_PLANKS:CRIMSON_HANGING_SIGN:1"
    - "CRIMSON_PLANKS:CRIMSON_PRESSURE_PLATE:1"
    - "CRIMSON_PLANKS:CRIMSON_SIGN:1"
    - "CRIMSON_PLANKS:CRIMSON_SLAB:2"
    - "CRIMSON_PLANKS:CRIMSON_STAIRS:1"
    - "CRIMSON_PLANKS:CRIMSON_TRAPDOOR:1"
    - "CRIMSON_PLANKS:CRIMSON_SHELF:1"

    ## warped
    - "WARPED_PLANKS:WARPED_BUTTON:4"
    - "WARPED_PLANKS:WARPED_DOOR:1"
    - "WARPED_PLANKS:WARPED_FENCE:1"
    - "WARPED_PLANKS:WARPED_FENCE_GATE:1"
    - "WARPED_PLANKS:WARPED_HANGING_SIGN:1"
    - "WARPED_PLANKS:WARPED_PRESSURE_PLATE:1"
    - "WARPED_PLANKS:WARPED_SIGN:1"
    - "WARPED_PLANKS:WARPED_SLAB:2"
    - "WARPED_PLANKS:WARPED_STAIRS:1"
    - "WARPED_PLANKS:WARPED_TRAPDOOR:1"
    - "WARPED_PLANKS:WARPED_SHELF:1"

    ## mangrove
    - "MANGROVE_PLANKS:MANGROVE_BUTTON:4"
    - "MANGROVE_PLANKS:MANGROVE_DOOR:1"
    - "MANGROVE_PLANKS:MANGROVE_FENCE:1"
    - "MANGROVE_PLANKS:MANGROVE_FENCE_GATE:1"
    - "MANGROVE_PLANKS:MANGROVE_HANGING_SIGN:1"
    - "MANGROVE_PLANKS:MANGROVE_PRESSURE_PLATE:1"
    - "MANGROVE_PLANKS:MANGROVE_SIGN:1"
    - "MANGROVE_PLANKS:MANGROVE_SLAB:2"
    - "MANGROVE_PLANKS:MANGROVE_STAIRS:1"
    - "MANGROVE_PLANKS:MANGROVE_TRAPDOOR:1"
    - "MANGROVE_PLANKS:MANGROVE_SHELF:1"

    ## cherry
    - "CHERRY_PLANKS:CHERRY_BUTTON:4"
    - "CHERRY_PLANKS:CHERRY_DOOR:1"
    - "CHERRY_PLANKS:CHERRY_FENCE:1"
    - "CHERRY_PLANKS:CHERRY_FENCE_GATE:1"
    - "CHERRY_PLANKS:CHERRY_HANGING_SIGN:1"
    - "CHERRY_PLANKS:CHERRY_PRESSURE_PLATE:1"
    - "CHERRY_PLANKS:CHERRY_SIGN:1"
    - "CHERRY_PLANKS:CHERRY_SLAB:2"
    - "CHERRY_PLANKS:CHERRY_STAIRS:1"
    - "CHERRY_PLANKS:CHERRY_TRAPDOOR:1"
    - "CHERRY_PLANKS:CHERRY_SHELF:1"

    ## bamboo
    - "BAMBOO_PLANKS:BAMBOO_BUTTON:4"
    - "BAMBOO_PLANKS:BAMBOO_DOOR:1"
    - "BAMBOO_PLANKS:BAMBOO_FENCE:1"
    - "BAMBOO_PLANKS:BAMBOO_FENCE_GATE:1"
    - "BAMBOO_PLANKS:BAMBOO_HANGING_SIGN:1"
    - "BAMBOO_PLANKS:BAMBOO_PRESSURE_PLATE:1"
    - "BAMBOO_PLANKS:BAMBOO_SIGN:1"
    - "BAMBOO_PLANKS:BAMBOO_SLAB:2"
    - "BAMBOO_PLANKS:BAMBOO_STAIRS:1"
    - "BAMBOO_PLANKS:BAMBOO_TRAPDOOR:1"
    - "BAMBOO_PLANKS:BAMBOO_SHELF:1"

    # Bamboo mosaic
    - "BAMBOO_PLANKS:BAMBOO_MOSAIC:1"
    - "BAMBOO_PLANKS:BAMBOO_MOSAIC_SLAB:2"
    - "BAMBOO_PLANKS:BAMBOO_MOSAIC_STAIRS:1"
    - "BAMBOO_MOSAIC:BAMBOO_MOSAIC_SLAB:2"
    - "BAMBOO_MOSAIC:BAMBOO_MOSAIC_STAIRS:1"

    # bricks
    - "BRICKS:BRICK:4"
    - "BRICK_SLAB:BRICK:2"
    - "BRICK_STAIRS:BRICK:4"
    - "BRICK_WALL:BRICK:4"

    # Prismarine
    - "PRISMARINE:PRISMARINE_SHARD:4"
    - "PRISMARINE_BRICKS:PRISMARINE_SHARD:9"
    - "DARK_PRISMARINE:PRISMARINE_SHARD:8"

    # Sandstone
    - "SANDSTONE:SAND:4"
    - "SMOOTH_SANDSTONE:SANDSTONE:1"
    - "SMOOTH_SANDSTONE:SAND:4"

    # Quarz
    - "QUARTZ_BLOCK:QUARTZ_BRICKS:1"
    - "QUARTZ_BLOCK:QUARTZ:4"
    - "SMOOTH_QUARTZ:QUARTZ_BLOCK:1"
    - "SMOOTH_QUARTZ:QUARTZ:4"

    # Nether bricks
    - "NETHER_BRICKS:NETHER_BRICK:4"
    - "NETHER_BRICK_FENCE:NETHER_BRICK:3"
    - "NETHER_BRICK_STAIRS:NETHER_BRICK:4"
    - "NETHER_BRICK_SLAB:NETHER_BRICK:2"
    - "NETHER_BRICK_WALL:NETHER_BRICK:4"
    - "CHISELED_NETHER_BRICKS:NETHER_BRICK:4"
    - "CRACKED_NETHER_BRICKS:NETHER_BRICK:4"

    # Andesite
    - "POLISHED_ANDESITE:ANDESITE:4"

    # Drionite
    - "POLISHED_DIORITE:DIORITE:4"

    # Granite
    - "POLISHED_GRANITE:GRANITE:4"